2025-06-08 11:44:18,088 - INFO - Prediction done in 0.4254s: {'class_': 'Spider_mites_Two_spotted_spider_mite', 'confidence': 0.9999468326568604}
2025-06-08 11:44:46,089 - INFO - Prediction done in 0.104s: {'class_': 'Early_blight', 'confidence': 0.9992238283157349}
2025-06-08 11:46:45,121 - INFO - Prediction done in 0.4897s: {'class_': 'Early_blight', 'confidence': 0.9992238283157349}
2025-06-08 11:46:45,122 - ERROR - Prediction failed
Traceback (most recent call last):
  File "c:\Users\sagni\OneDrive\Documents\Tomato-Disease-Classification\api\main.py", line 69, in predict
    return PredictionResponse(**prediction)
  File "C:\Users\sagni\AppData\Local\Programs\Python\Python39\lib\site-packages\pydantic\main.py", line 253, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 2 validation errors for PredictionResponse
Class
  Field required [type=missing, input_value={'class_': 'Early_blight'...ce': 0.9992238283157349}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
Confidence
  Field required [type=missing, input_value={'class_': 'Early_blight'...ce': 0.9992238283157349}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.11/v/missing
2025-06-08 11:47:53,016 - INFO - Prediction done in 0.4206s: {'Class': 'Early_blight', 'Confidence': 0.9992238283157349}
2025-06-08 11:48:24,567 - INFO - Prediction done in 0.1626s: {'Class': 'mosaic_virus', 'Confidence': 0.9999402761459351}
2025-06-08 11:53:14,107 - INFO - Model info endpoint hit. Responding with model path and number of classes.
2025-06-08 19:57:51,072 - DEBUG - Using proactor: IocpProactor
2025-06-08 19:58:01,882 - INFO - Model info endpoint hit. Responding with model path and number of classes.
2025-06-08 19:58:09,728 - DEBUG - /health endpoint called
2025-06-08 19:59:47,012 - DEBUG - Calling on_part_begin with no data
2025-06-08 19:59:47,012 - DEBUG - Calling on_header_field with data[54:73]
2025-06-08 19:59:47,013 - DEBUG - Calling on_header_value with data[75:164]
2025-06-08 19:59:47,013 - DEBUG - Calling on_header_end with no data
2025-06-08 19:59:47,014 - DEBUG - Calling on_header_field with data[166:178]
2025-06-08 19:59:47,014 - DEBUG - Calling on_header_value with data[180:190]
2025-06-08 19:59:47,014 - DEBUG - Calling on_header_end with no data
2025-06-08 19:59:47,014 - DEBUG - Calling on_headers_finished with no data
2025-06-08 19:59:47,014 - DEBUG - Calling on_part_data with data[194:20351]
2025-06-08 19:59:47,015 - DEBUG - Calling on_part_end with no data
2025-06-08 19:59:47,015 - DEBUG - Calling on_end with no data
2025-06-08 19:59:47,605 - INFO - Prediction done in 0.5879s: {'Class': 'mosaic_virus', 'Confidence': 0.9999995231628418}
2025-06-08 20:00:17,943 - DEBUG - /health endpoint called
